name: CI for FluentUtils
on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  calculate-version:
    name: Calculate version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      nuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

  publish-valueObject:
    runs-on: ubuntu-latest
    needs: calculate-version
    name: Publish ValueObject NuGet Package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Setup .NET Core Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/draekien/index.json
          dotnet-version: '6.0.x'
          include-prerelease: true
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pack
        run: cd src/FluentUtils.ValueObject && dotnet pack -c Release -o out -p:PackageVersion=${{ needs.calculate-version.outputs.nuGetVersionV2 }}

      - name: Publish
        run: dotnet nuget push ./src/FluentUtils.ValueObject/out/*.nupkg --skip-duplicate

  publish-autoMapper:
    runs-on: ubuntu-latest
    needs: calculate-version
    name: Publish AutoMapper NuGet Package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Setup .NET Core Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/draekien/index.json
          dotnet-version: '6.0.x'
          include-prerelease: true
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pack
        run: cd src/FluentUtils.AutoMapper && dotnet pack -c Release -o out -p:PackageVersion=${{ needs.calculate-version.outputs.nuGetVersionV2 }}

      - name: Publish
        run: dotnet nuget push ./src/FluentUtils.AutoMapper/out/*.nupkg --skip-duplicate

  publish-autoMapper-Extensions:
    runs-on: ubuntu-latest
    needs: calculate-version
    name: Publish AutoMapper Extensions NuGet Package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Setup .NET Core Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/draekien/index.json
          dotnet-version: '6.0.x'
          include-prerelease: true
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pack
        run: cd src/FluentUtils.AutoMapper.Extensions.Microsoft.DependencyInjection && dotnet pack -c Release -o out -p:PackageVersion=${{ needs.calculate-version.outputs.nuGetVersionV2 }}

      - name: Publish
        run: dotnet nuget push ./src/FluentUtils.AutoMapper.Extensions.Microsoft.DependencyInjection/out/*.nupkg --skip-duplicate
